### DISCUSSION TITLE
Valetudo configuration url

### DISCUSSION THREAD

**Discussion by Barbedx** [Hypfer/Valetudo#1831] [Q&A / Support] [answered]
In my vacuum, I receive an MQTT topic with a DNS name for configuration_url. However, there seems to be an issue in my network that prevents its usage. It's says "valetudo-chubbypunywoodcock.local’s server IP address could not be found." As a result, the button in Home Assistant doesn't work, and I have to manually enter the IP address to access the device. Is it possible to change the configuration_url value to the device's IP address?

```
device:
  manufacturer: Roborock
  model: V1
  name: Saniok
  identifiers:
    - ChubbyPunyWoodcock
  sw_version: 2023.03.0 (Valetudo)
  configuration_url: http://valetudo-chubbypunywoodcock.local
```
