### DISCUSSION TITLE
trigger "Map Reset"

### DISCUSSION THREAD

**Discussion by pszypowicz** [Hypfer/Valetudo#1857] [Q&A / Support] [answered]
Hello everyone,

Sometimes, over time, my dockbase for Z10 Pro will start to rotate. Even if that is just 5 degrees, I will try to break saved map, and vacuum will start to go in diagonal lines, and skip places on the floor. 

The current "fix" for me, is to visit web ui of valetudo and manually click "reset map".

Would it be possible to trigger "map reset" via mqtt command (preffereably from HA UI), or via some API HTTP request?

**Comment by Hypfer** [comment, marked as answer]
https://github.com/Hypfer/Valetudo/blob/ed051c69a5decfc8db09e3c829a5077ad68b290a/backend/lib/webserver/capabilityRouters/doc/MapResetCapabilityRouter.openapi.json#L2-L34

**Reply by pszypowicz** [reply]
Thank you very much! 

I added such code to my configuration.yaml in home assistant:

```
 vacuum_map_reset:
    url: http://192.168.x.x/api/v2/robot/capabilities/MapResetCapability
    method: PUT
    payload: '{"action":"reset"}'
    content_type:  'application/json'
```
