### ISSUE TITLE
Returning home during cleaning stage requires pausing first

### ISSUE THREAD

**Issue by tlpbu** [Hypfer/Valetudo#1012]
## Describe the bug
If any vacuum is perfoming cleaning, return home mqtt command is ignored unless paused inbetween.

## To Reproduce
Home Assistant automation that has worked for years but now is just not doing anything without any errors logged
```
- alias: Send Servantess to dock when someone arrives home during repeated cleanup
  trigger:
    - platform: state
      entity_id: group.family
      to: 'home'
  condition:
...
  action:
    - service: vacuum.return_to_base
      entity_id: vacuum.servantess
```

### Vacuum Model
RoborockV1ValetudoRobot

### Valetudo Version
2021.07.1

## Expected behavior
React on BasicControlCapability mqtt command HOME without pausing vacuum.

## Additional context
This was working for years until I upgraded Valetudo from 2021.06.2 to 2021.07.1. So behaviour has changed in later relases.
