### ISSUE TITLE
Zoned_cleanup + Go_to via MQTT

### ISSUE THREAD

**Issue by AS137430** [Hypfer/Valetudo#204]
I am new to Valetudo, please help me understand. From Home Assistant 0.92.1, I am sending this via MQTT
```
service: vacuum.send_command
        data:
          entity_id: 'vacuum.rockrobo'
          command: 'zoned_cleanup'
          params:
            'zone_id': 'guest room'
```
In MqttClient.js, from these lines:
```
  if(msg && msg.command) {
        switch(msg.command) {
            case "zoned_cleanup":
                if(msg.zone_id) {
                    const areas = this.configuration.get("areas");
                    const zone = areas.find(e => Array.isArray(e) && e[0] === msg.zone_id);

                    if(zone) {
                        this.vacuum.startCleaningZone(zone, () => {});
                    }
```
Shouldn't this be:
```
if(msg && msg.command) {
        switch(msg.command) {
            case "zoned_cleanup":
                if(msg.zone_id) {
                    const areas = this.configuration.get("areas");
                    const zone = areas.find(e => Array.isArray(e) && e[0] === msg.zone_id);
	            //console.log(zone);
                    if(zone) {
                        this.vacuum.startCleaningZone(zone[1], () => {});
                    }
```
As contents of zone is
```
[ 'guest room', [ [ 25045, 25217, 28130, 29447, 1 ] ] ]
```
as zone_id is zone[0] and zone[1] is the array. Or am I confused?
