### ISSUE TITLE
reset_consumables in Home Assistant

### ISSUE THREAD

**Issue by JohanAke1** [Hypfer/Valetudo#407]
Hi,
I'm trying to get reset_consumables to work in home assistant with service call. But it won't change anything in Valetudo side. Could anyone point me where I have an error?
Here is my script:
```
script:
  reset_sensor:
    alias: "Reset sensor consumable"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: 'vacuum.xiaomi'
          command: 'reset_consumable'
          params:
            'consumable': 'sensor_dirty_time'
```

No idea what the params should be where I have "consumable"... No errors on the script but nothing changes.

On Valetudo logs I get only

"Received invalid custom command reset_consumable { command: 'reset_consumable', consumable: 'sensor_dirty_time' }
