### ISSUE TITLE
Configure Iterations for Zoned Cleanup

### ISSUE THREAD

**Issue by Hypfer** [Hypfer/Valetudo#521]
Both saved zones as well as dynamically drawn ones are currently missing the option to configure the Iteration count.

**Comment by Hypfer** [comment]
This only needs UI Support. The backend already supports this parameter

**Comment by IronicBadger** [comment]
If the backend already supports this, presumably I could call this via `mqtt.publish` like so:

```
service: mqtt.publish
data:
  topic: valetudo/robovacDown/MapSegmentationCapability/clean/set
  payload: '["17", "20"]'
```

What would the payload need to be to clean zone 17 3 times say?
