### ISSUE TITLE
Zone cleanup stops after several seconds due to "Some of reached areas are not cleaned"

### ISSUE THREAD

**Issue by tlpbu** [Hypfer/Valetudo#715]
## Describe the bug

Starting zone cleanup from Home Assistant 
```
                action: call-service
                service: vacuum.send_command
                service_data:
                  entity_id: vacuum.robot
                  command: 'zoned_cleanup'
                  params:
                    'zone_ids': ['85318723-5b9e-4d45-9d33-09828dc3ee9d']
```
Vacuum starts cleaning with audial notification "Starting zone cleanup"
but then after several seconds return to dock saying "Some of reached areas are not cleaned".

In Valetudo logs file there is potentially related entry
```
[2021-02-27T07:07:20.794Z] [INFO] Unknown cloud message received: {"method":"event.zoned_clean_partial_done","params":[0],"id":551861551}
```

## To Reproduce

Not really clear how to reproduce - zone cleanup works fine until it doesn't
### Vacuum Model

Xiaomi Roborock Gen 1

### Valetudo Version

2021.2.0

## Additional context

"Full" clean command works no problem.

Could be it is not even Valetudo bug as such, because here https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/295 it is happening in another context.
